---
title: "Download water quality data using API for selected local authority areas"
author: "Gosia Szkatula"
date: today
output:
    html_document: default
    pdf_document: default
---

# References

- Data retrieval approach adapted from existing work by:

  [Westcountry Rivers Trust – EA Water Quality API example] <br>
  https://github.com/Westcountry-Rivers-Trust/Get_EA_WaterQuality_R


- Environment Agency Water Quality API:

  https://environment.data.gov.uk/water-quality <br>
  https://environment.data.gov.uk/water-quality/api-docs



- Local authority areas: 
  https://www.ons.gov.uk/aboutus/transparencyandgovernance/freedomofinformationfoi/lookuptableforukauthoritycodes2024

- Selected local authority areas: 

    - E06000035	Medway 
    - E07000064	Rother
    - E06000046	Isle of Wight
    - E07000091	New Forest

```{r}
options(repos = c(CRAN = "https://cloud.r-project.org/"))

## pacman::p_load() loads packages, and also installs them if you don't have them
if(!require(pacman)) install.packages("pacman")

pacman::p_load(
  readr,
  httr, 
  jsonlite, 
  purrr, 
  tidylog,
  dplyr,
  stringr,
  tidyr,
  lubridate,
  beepr
)
```


```{r}
#| eval: false
# Set up the function -----------------------------------------------------

## The new EA water quality API has some limitations compared to the previous version.
# The maximum limit per call is 2500 (or less, depending on which "Accept" option is used).
# A maximum of one year of data can be called at one time.
# Multiple determinands cannot be requested simultaneously.

## This function loops through API calls month-by-month, to get around the limits.
# Also converts phenomenonTime to POSIXct, and adds a separate Date column.

getdata_eawq <- function(area, determinand, start_date, end_date){
  
  # Generate sequence of month starts
  month_starts <- seq(start_date, end_date, by = "month")
  month_ends <- c(month_starts[-1] - 1, end_date)
  
  # Initialize empty list to store results
  data_list <- list()
  
  # Loop through each month
  for (i in seq_along(month_starts)) {
    
    # Message to let the user know what's happening
    cat("Getting data for:", format(month_starts[i], "%Y-%m"), "\n")
    
    # API call
    response <- POST(
      "https://environment.data.gov.uk/water-quality/data/observation?",
      query = list(
        determinand = determinand, 
        dateFrom = format(month_starts[i], "%Y-%m-%d"),
        dateTo = format(month_ends[i], "%Y-%m-%d"),
        limit = 2500,
        precannedArea = area
      ), 
      add_headers(Accept = "text/csv")
    )
    
    # Extract content
    data_list[[i]] <- content(response, as = "text", encoding = "UTF-8")
    
    # Add a half-second delay to help keep the API running smoothly
    Sys.sleep(0.5)
  }
  
  # Combine all months into single dataframe
  # Set everything to character to avoid binding issues related to non-numeric results (e.g. "<1"). This can be dealt with later once you've got the data. 
  bind_rows(
    lapply(data_list, function(x) {
      tryCatch(
        read.csv(text = x, colClasses = "character"), 
        error=function(e) NULL
      )
    })
  ) %>% 
    drop_na(result) %>% # Get rid of any dodgy rows
    mutate(phenomenonTime = as_datetime(phenomenonTime)) %>% # Convert to POSIXct
    mutate(Date = as_date(phenomenonTime)) # Add a Date column
}
```

```{r}
### Date range
## Make sure you follow this format: "YYYY-MM-DD", or use Sys.Date() for today's date.
## Sys.Date() can also be modified for time relative to the present, e.g. Sys.Date()-7 is a week ago.
start_date <- as.Date("2020-01-01")
end_date <- as.Date("2025-12-31")
```

# E06000035	Medway

```{r}
#| eval: false
# For local authority areas, use "local_authority,[CODE]", e.g. "local_authority,E06000002"
# https://www.ons.gov.uk/aboutus/transparencyandgovernance/freedomofinformationfoi/lookuptableforukauthoritycodes2024
area <- "local_authority,E06000035"

#### Get the data for each determinand 

# pH Water; pH of Water
ph <- getdata_eawq(
  area=area,  
  determinand="0061",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`pH Water` = result)

# Temp Water; Temperature of Water
temp <- getdata_eawq(
  area=area, 
  determinand="0076",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`Temp Water` = result)

# Cond @ 25C;Conductivity at 25 C
cond <- getdata_eawq(
  area=area,  
  determinand="0077",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`Cond @ 25C` = result)

#### Join the data frames together and export as CSV 

### Create a list of the data frames
df_list <- list(ph, temp, cond)

### Remove columns that are specific to determinands and join the data frames
wq_data <- lapply(df_list, function(x) {
  x %>% 
    select(-c(id, determinand.notation, determinand.prefLabel, unit))
}) %>% 
  reduce(full_join) %>% 
  arrange(samplingPoint.region, samplingPoint.area, samplingPoint.subArea, samplingPoint.prefLabel, Date) %>% 
  relocate(Date)

### Export the dataset as a CSV
write_csv(wq_data, "data/E06000035_Medway.csv")
```

# E07000064	Rother

```{r}
#| eval: false
area <- "local_authority,E07000064"

#### Get the data for each determinand 

# pH Water; pH of Water
ph <- getdata_eawq(
  area=area,  
  determinand="0061",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`pH Water` = result)

# Temp Water; Temperature of Water
temp <- getdata_eawq(
  area=area, 
  determinand="0076",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`Temp Water` = result)

# Cond @ 25C;Conductivity at 25 C
cond <- getdata_eawq(
  area=area,  
  determinand="0077",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`Cond @ 25C` = result)

#### Join the data frames together and export as CSV 

### Create a list of the data frames
df_list <- list(ph, temp, cond)

### Remove columns that are specific to determinands and join the data frames
wq_data <- lapply(df_list, function(x) {
  x %>% 
    select(-c(id, determinand.notation, determinand.prefLabel, unit))
}) %>% 
  reduce(full_join) %>% 
  arrange(samplingPoint.region, samplingPoint.area, samplingPoint.subArea, samplingPoint.prefLabel, Date) %>% 
  relocate(Date)

### Export the dataset as a CSV
write_csv(wq_data, "data/E07000064_Rother.csv")
```

# E06000046	Isle of Wight

```{r}
#| eval: false
area <- "local_authority,E06000046"

#### Get the data for each determinand 

# pH Water; pH of Water
ph <- getdata_eawq(
  area=area,  
  determinand="0061",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`pH Water` = result)

# Temp Water; Temperature of Water
temp <- getdata_eawq(
  area=area, 
  determinand="0076",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`Temp Water` = result)

# Cond @ 25C;Conductivity at 25 C
cond <- getdata_eawq(
  area=area,  
  determinand="0077",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`Cond @ 25C` = result)

#### Join the data frames together and export as CSV 

### Create a list of the data frames
df_list <- list(ph, temp, cond)

### Remove columns that are specific to determinands and join the data frames
wq_data <- lapply(df_list, function(x) {
  x %>% 
    select(-c(id, determinand.notation, determinand.prefLabel, unit))
}) %>% 
  reduce(full_join) %>% 
  arrange(samplingPoint.region, samplingPoint.area, samplingPoint.subArea, samplingPoint.prefLabel, Date) %>% 
  relocate(Date)

### Export the dataset as a CSV
write_csv(wq_data, "data/E06000046_Isle_of_Wight.csv")
```

# E07000091	New Forest

```{r}
#| eval: false
area <- "local_authority,E07000091"

#### Get the data for each determinand 

# pH Water; pH of Water
ph <- getdata_eawq(
  area=area,  
  determinand="0061",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`pH Water` = result)

# Temp Water; Temperature of Water
temp <- getdata_eawq(
  area=area, 
  determinand="0076",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`Temp Water` = result)

# Cond @ 25C;Conductivity at 25 C
cond <- getdata_eawq(
  area=area,  
  determinand="0077",
  start_date=start_date, 
  end_date=end_date
) %>% 
  rename(`Cond @ 25C` = result)

#### Join the data frames together and export as CSV 

### Create a list of the data frames
df_list <- list(ph, temp, cond)

### Remove columns that are specific to determinands and join the data frames
wq_data <- lapply(df_list, function(x) {
  x %>% 
    select(-c(id, determinand.notation, determinand.prefLabel, unit))
}) %>% 
  reduce(full_join) %>% 
  arrange(samplingPoint.region, samplingPoint.area, samplingPoint.subArea, samplingPoint.prefLabel, Date) %>% 
  relocate(Date)

### Export the dataset as a CSV
write_csv(wq_data, "data/E07000091_New_Forest.csv")
```